name: context-var
on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Print context variable
        run: |
         echo "The event that triggered this workflow is ${{ github.event_name }}"
         echo "The branch that triggered this workflow is ${{ github.ref }}"
         echo "The PR head ref is ${{ github.event.pull_request.head.ref }}"