name: context-var
on:
  push:
    branches:
      - main
      - master
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Print context variable
        run: echo "The event that triggered this workflow is ${{ github.event_name }}"